import React, { useState } from "react";
import { useLocation } from "react-router-dom";
import jsPDF from "jspdf";
import "jspdf-autotable";

const ExportPage = () => {
  const location = useLocation();
  const pitchData = location.state?.pitch || null;
  const [loading, setLoading] = useState(false);

  const downloadPDF = () => {
    if (!pitchData) return alert("No pitch data found!");
    setLoading(true);

    const doc = new jsPDF();

    // 🧾 Title Section
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("PitchCraft - AI Startup Pitch", 14, 20);

    // 🎯 Info Section
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Startup Name: ${pitchData.startupName}`, 14, 40);
    doc.text(`Tagline: ${pitchData.tagline}`, 14, 50);

    // 🧩 Pitch Section
    doc.setFont("helvetica", "bold");
    doc.text("Pitch:", 14, 65);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(pitchData.pitch, 180), 14, 72);

    // 👥 Audience Section
    doc.setFont("helvetica", "bold");
    doc.text("Target Audience:", 14, 105);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(pitchData.targetAudience, 180), 14, 112);

    // 🎨 Color Palette Idea
    if (pitchData.colorPaletteIdea) {
      doc.setFont("helvetica", "bold");
      doc.text("Color Palette Idea:", 14, 145);
      doc.setFont("helvetica", "normal");
      doc.text(doc.splitTextToSize(pitchData.colorPaletteIdea, 180), 14, 152);
    }

    // 📅 Footer
    doc.setFontSize(10);
    doc.text("Generated by PitchCraft AI Assistant", 14, 280);

    doc.save(`${pitchData.startupName || "PitchCraft"}_Pitch.pdf`);
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-indigo-100 flex flex-col items-center justify-center px-4 py-10">
      <div className="w-full max-w-3xl bg-white/70 backdrop-blur-lg border border-gray-100 shadow-2xl rounded-3xl p-8 text-center animate-fadeIn">
        {/* 🧠 Illustration */}
        <img
          src="public/images-removebg-preview.png"
          alt="AI Export"
          className="w-40 mx-auto mb-6 drop-shadow-lg animate-float"
        />

        <h1 className="text-3xl font-bold text-indigo-700 mb-4">
          📄 Export Your AI Pitch
        </h1>
        <p className="text-gray-600 mb-8 max-w-lg mx-auto">
          Review your AI-generated pitch below and export it as a beautifully
          formatted PDF report in one click.
        </p>

        {/* 📋 Pitch Details */}
        {pitchData ? (
          <>
            <div className="text-left bg-gradient-to-br from-gray-50 to-white border border-gray-200 p-6 rounded-2xl shadow-inner mb-8 transition-all hover:shadow-md">
              <p className="text-2xl font-bold text-indigo-700 mb-2">
                {pitchData.startupName}
              </p>
              <p className="italic text-gray-500 mb-4">"{pitchData.tagline}"</p>
              <div className="space-y-3 text-gray-700">
                <p>
                  <strong>🎯 Pitch:</strong> {pitchData.pitch}
                </p>
                <p>
                  <strong>👥 Audience:</strong> {pitchData.targetAudience}
                </p>
                {pitchData.colorPaletteIdea && (
                  <p>
                    <strong>🎨 Color Palette:</strong>{" "}
                    {pitchData.colorPaletteIdea}
                  </p>
                )}
              </div>
            </div>

            {/* 🖨 Download Button */}
            <button
              onClick={downloadPDF}
              disabled={loading}
              className={`relative inline-flex items-center justify-center w-full md:w-auto px-8 py-3 font-semibold rounded-xl text-white transition-all duration-300 ${
                loading
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-indigo-600 hover:bg-indigo-700 hover:scale-[1.02] shadow-lg"
              }`}
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <svg
                    className="animate-spin h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8v8z"
                    ></path>
                  </svg>
                  Generating PDF...
                </span>
              ) : (
                "⬇️ Download as PDF"
              )}
            </button>
          </>
        ) : (
          <div className="text-gray-600 mt-6">
            <p className="text-lg mb-2">No pitch data to export 😕</p>
            <a
              href="/create"
              className="text-indigo-600 font-semibold hover:underline"
            >
              Go back & create a new pitch
            </a>
          </div>
        )}
      </div>

      {/* Footer */}
      <footer className="mt-12 text-gray-500 text-sm text-center">
        © {new Date().getFullYear()} PitchCraft AI — Designed by Nexa ⚡
      </footer>
    </div>
  );
};

export default ExportPage;
